# Full CI values. Triton starts at 0 replicas; RepositoryIndex scales the first pod.
scaleFromZero:
  enabled: true

triton:
  image: fastml/triton-torchgeo:26.04-py3-geometric # works for CMSSW run3
  args: 
    - |
      /opt/tritonserver/bin/tritonserver \
      --model-repository=/cvmfs/cms.cern.ch/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre7/external/el9_amd64_gcc12/data/RecoBTag/Combined/data/models/ \
      --log-verbose=0 \
      --disable-auto-complete-config \
      --exit-timeout-secs=60
  resources:
    limits: { cpu: 1, memory: 3Gi}
    requests: { cpu: 1, memory: 1Gi}
  modelRepository:
    enabled: true
    storageType: cvmfs-pvc
    mountPath: /cvmfs
  readinessProbe:
    reset: true

envoy:
  resources:
    requests:
      cpu: 0.1
      memory: "128Mi"
  service:
    type: LoadBalancer
  rate_limiter:
    listener_level:
      enabled: true

keda:
  enabled: true
  minReplicaCount: 0
  maxReplicaCount: 2
  pollingInterval: 5
  cooldownPeriod: 5
  scaleDown:
    stabilizationWindowSeconds: 0
    periodSeconds: 15
    stepsize: 1

prometheus:
  enabled: true

grafana:
  enabled: true

metricsCollector:
  enabled: true