triton:
  replicas: 1
  # image: fastml/triton-torchgeo:21.02-py3-geometric # run2
  image: fastml/triton-torchgeo:22.07-py3-geometric # run3
  command: ["/bin/sh", "-c"]
  args: 
    - |
      /opt/tritonserver/bin/tritonserver \
      --model-repository=/cvmfs/cms.cern.ch/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre7/external/el9_amd64_gcc12/data/RecoBTag/Combined/data/models/ \
      --log-verbose=0 \
      --disable-auto-complete-config \
      --exit-timeout-secs=60
  resources:
    limits: { cpu: 1, memory: 3Gi}
    requests: { cpu: 1, memory: 3Gi}
  modelRepository:
    enabled: true
    storageType: cvmfs-pvc
    mountPath: /cvmfs
  resetReadinessProbe: true
envoy:
  enabled: true
  service:
    type: LoadBalancer
  rate_limiter:
    listener_level:
      enabled: true
      max_tokens: 5
      tokens_per_fill: 1
      fill_interval: 12s
prometheus:
  external: false
autoscaler:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
ingress:
  enabled: false
grafana:
  enabled: true
