apiVersion: v1
kind: Service
metadata:
  name: {{ include "supersonic.inferenceServerName" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: inference-server
    {{- if .Values.inferenceServer.service.labels }}
{{ toYaml .Values.inferenceServer.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.inferenceServer.service.annotations }}
{{ toYaml .Values.inferenceServer.service.annotations | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  ports:
  {{- range .Values.inferenceServer.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: inference-server