{{ if .Values.common.cvmfsPvc | default false }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1
  storageClassName: cvmfs

{{ end }}