{{ if eq .Values.triton.modelRepository.storageType "cvmfs-pvc" }}
{{- $mypvc := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace (printf "cvmfs")) }}
{{- if not $mypvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1
  storageClassName: cvmfs
{{ end }}
{{ end }}