{{- range .Values.servers }}

{{- if .envoy.enabled }}

{{- $envoyGrpcPort := "" -}}
{{- range $.Values.common.envoyService.ports -}}
  {{- if eq .name "grpc" -}}
    {{- $envoyGrpcPort = .port -}}
  {{- end -}}
{{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .envoy.name }}
spec:
  replicas: {{ .envoy.replicas }}
  selector:
    matchLabels:
      app: {{ .envoy.name }}
  template:
    metadata:
      labels:
        app: {{ .envoy.name }}
    spec:
      containers:
      - name: envoy
        image: {{ .envoy.image }}
        args: {{ toYaml .envoy.args | nindent 10 }}
        ports:
        - containerPort: {{ $envoyGrpcPort }}
        volumeMounts:
        - name: {{ .envoy.name }}-envoy-config
          mountPath: /etc/envoy
        - name: {{ .envoy.name }}-lua-volume
          mountPath: /etc/envoy/lua
          readOnly: true
        resources:
          {{ toYaml .envoy.resources | nindent 10 }}
      volumes:
      - name: {{ .envoy.name }}-envoy-config
        configMap:
          name: {{ .envoy.name }}-envoy-config
      - name: {{ .envoy.name }}-lua-volume
        configMap:
          name: {{ .envoy.name }}-lua-config
          items:
          - key: envoy-filter.lua
            path: envoy-filter.lua


{{- if $.Values.common.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.common.nodeSelector | nindent 8 }}
{{- end }}
{{- if $.Values.common.tolerations }}
      tolerations:
{{ toYaml $.Values.common.tolerations | nindent 8 }}
{{- end }}
      restartPolicy: Always

---

{{- end }}

{{- end }}