{{- range .Values.servers }}

{{- if .envoy.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .envoy.name }}
  labels:
{{ toYaml $.Values.common.envoyService.labels | nindent 4 }}
    app: {{ .envoy.name }}
spec:
  type:  {{ $.Values.common.envoyService.type }}
  selector:
    app: {{ .envoy.name }}
  ports:
  {{- range $.Values.common.envoyService.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
---

{{- end }}

{{- end }}
