{{- if .Values.envoy.enabled }}

{{- $envoyGrpcPort := "" -}}
{{- range .Values.envoy.service.ports -}}
  {{- if eq .name "grpc" -}}
    {{- $envoyGrpcPort = .port -}}
  {{- end -}}
{{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supersonic.envoyName" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: envoy
spec:
  replicas: {{ .Values.envoy.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ include "supersonic.name" . }}
      app.kubernetes.io/component: envoy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ include "supersonic.name" . }}
        app.kubernetes.io/component: envoy
    spec:
      containers:
      - name: envoy
        image: {{ .Values.envoy.image }}
        args: {{ toYaml .Values.envoy.args | nindent 10 }}
        ports:
        - containerPort: {{ $envoyGrpcPort }}
        volumeMounts:
        - name: {{ include "supersonic.name" . }}-envoy-config
          mountPath: /etc/envoy
        {{- if .Values.envoy.rate_limiter.prometheus_based.enabled }}
        - name: {{ include "supersonic.name" . }}-lua-volume
          mountPath: /etc/envoy/lua
          readOnly: true
        {{- end }}
        resources:
          {{ toYaml .Values.envoy.resources | nindent 10 }}
      volumes:
      - name: {{ include "supersonic.name" . }}-envoy-config
        configMap:
          name: {{ include "supersonic.name" . }}-envoy-config
      {{- if .Values.envoy.rate_limiter.prometheus_based.enabled }}
      - name: {{ include "supersonic.name" . }}-lua-volume
        configMap:
          name: {{ include "supersonic.name" . }}-lua-config
          items:
          - key: envoy-filter.lua
            path: envoy-filter.lua
      {{- end }}


{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
{{- end }}
      restartPolicy: Always

---

{{- end }}