{{- if .Values.envoy.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envoy.name }}
  labels:
{{ toYaml .Values.envoy.service.labels | nindent 4 }}
    app: {{ .Values.envoy.name }}
spec:
  type:  {{ .Values.envoy.service.type }}
  selector:
    app: {{ .Values.envoy.name }}
  ports:
  {{- range .Values.envoy.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
---

{{- end }}