{{ if .Values.ingress.enabled | default false }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "supersonic.fullname" . }}-ingress-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "supersonic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    haproxy-ingress.github.io/cors-enable: "true"
    haproxy-ingress.github.io/backend-protocol: "h2"
    haproxy-ingress.github.io/proxy-body-size: "512m"
    haproxy-ingress.github.io/timeout-client: "5m"
    haproxy-ingress.github.io/timeout-server: "5m"
    haproxy-ingress.github.io/timeout-connect: "5m"
    haproxy-ingress.github.io/timeout-http-request: "5m"
    haproxy-ingress.github.io/timeout-queue: "1m"
    haproxy-ingress.github.io/health-check-interval: "30s"
    haproxy-ingress.github.io/health-check-rise-count: "1"
spec:
  ingressClassName: haproxy
  tls:
  - hosts:
      - {{ .Values.ingress.hostName }}
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "supersonic.envoyName" . }}
            port:
              number: 8001
        path: /
        pathType: ImplementationSpecific

{{ end }}