apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "supersonic.fullname" . }}-triton-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "supersonic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: triton
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "supersonic.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: triton
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "supersonic.fullname" . }}-envoy-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "supersonic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: envoy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "supersonic.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: envoy
  endpoints:
  - port: admin
    path: /stats/prometheus
    interval: 15s