apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  {{ .Values.triton.name }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app:  {{ .Values.triton.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.triton.name }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  {{ .Values.envoy.name }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app:  {{ .Values.envoy.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.envoy.name }}
  endpoints:
  - port: admin
    path: /stats/prometheus
    interval: 15s