apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.triton.name }}
spec:
  replicas: {{ .Values.triton.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.triton.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.triton.name }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: triton-server
        image: {{ .Values.triton.image }}
        resources:
          {{ toYaml .Values.triton.resources | nindent 10 }}
        ports:
        {{- range .Values.triton.service.ports }}
        - name: {{ .name }}
          containerPort: {{ .port }}
          protocol: {{ .protocol }}
        {{- end }}
        volumeMounts:
          - name: model-repository
            mountPath: {{ .Values.triton.modelRepository.mountPath }}
            mountPropagation: HostToContainer
            readOnly: true
        command: {{ toYaml .Values.triton.command | nindent 10 }}
        args:  {{ toYaml .Values.triton.args | nindent 10 }}
        startupProbe:
          periodSeconds: 10
          failureThreshold: 12
          httpGet:
            path: /v2/health/ready
            port: http
        readinessProbe:
          exec:
            command: ["/bin/sh", "-c", "curl -sf http://localhost:8000/v2/health/ready > /dev/null && [ ! -f /tmp/shutdown ]"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "touch /tmp/shutdown; sleep 60"]
{{- if eq .Values.triton.modelRepository.storageType "nfs" }}
      volumes:
      - name: model-repository
        nfs:
          server: {{ .Values.triton.modelRepository.nfs.server }}
          path: {{ .Values.triton.modelRepository.nfs.path }}
{{- else if eq .Values.triton.modelRepository.storageType "pvc" }}
      volumes:
      - name: model-repository
        persistentVolumeClaim:
          claimName: {{ .Values.triton.modelRepository.pvc.claimName }}
{{- else if eq .Values.triton.modelRepository.storageType "cvmfs-hostPath" }}
      volumes:
      - name: model-repository
        hostPath: 
          path: /cvmfs
{{- else if eq .Values.triton.modelRepository.storageType "cvmfs-pvc" }}
      volumes:
      - name: model-repository
        persistentVolumeClaim:
          claimName: cvmfs
          readOnly: true
{{- end }}

{{- if .Values.triton.affinity }}
      affinity: {{ toYaml .Values.triton.affinity | nindent 8}}
{{- end }}

{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
{{- end }}
      restartPolicy: Always