{{- range .Values.servers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .triton.name }}
  labels:
{{ toYaml $.Values.common.tritonService.labels | nindent 4 }}
    app: {{ .triton.name }}
  annotations:
{{ toYaml $.Values.common.tritonService.annotations | nindent 4 }}
spec:
  clusterIP: None
  ports:
  {{- range $.Values.common.tritonService.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
  selector:
    app: {{ .triton.name }}
---
{{- end }}
