apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.triton.name }}
  labels:
{{ toYaml .Values.triton.service.labels | nindent 4 }}
    app: {{ .Values.triton.name }}
  annotations:
{{ toYaml .Values.triton.service.annotations | nindent 4 }}
spec:
  clusterIP: None
  ports:
  {{- range .Values.triton.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
  selector:
    app: {{ .Values.triton.name }}