{
 "title": "SuperSONIC Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "release",
    "label": "Release name",
    "query": {
     "query": "label_values(nv_inference_exec_count,release)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nv_inference_exec_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; background: transparent !important;\">\n  <img src=\"https://github.com/fastmachinelearning/SuperSONIC/blob/main/docs/img/SuperSONIC_small_light_256.png?raw=true\" \n       alt=\"SONIC Logo\" style=\"width: 100px; margin-right: 15px; display: inline-block;\">\n  <div style=\"display: inline-block;\">\n    <h1 style=\"margin: 0; padding: 0;\">SuperSONIC Dashboard</h1>\n   <div style=\"margin: 5px 0;\">\n      <a href=\"https://fastmachinelearning.org/SuperSONIC\" target=\"_blank\" \n         style=\"margin-right: 15px; text-decoration: none;\">\n        <i class=\"fa fa-book\"></i> Documentation\n      </a>\n      <a href=\"https://github.com/fastmachinelearning/SuperSONIC/issues\" target=\"_blank\" \n         style=\"margin-right: 15px; text-decoration: none;\">\n        <i class=\"fa fa-github\"></i> GitHub Issues\n      </a>\n   </div>\n  </div>\n</div>"
   }
  },
  { "title": "SuperSONIC Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Number of Inference Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(release)(nv_gpu_utilization{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"})",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Latency Breakdown",
   "type": "timeseries",
   "description": "Latency components measured by the inference servers, as well as total latency measured at proxy.",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_compute_infer_duration_us{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s])) / sum ((rate(nv_inference_exec_count{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s]) * 1000))",
     "legendFormat": "Inference"
    },
    {
     "expr": "sum (rate(nv_inference_queue_duration_us{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s])) / sum ((rate(nv_inference_exec_count{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s]) * 1000))",
     "legendFormat": "Queue"
    },
    {
     "expr": "sum (rate(nv_inference_compute_input_duration_us{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s])) / sum ((rate(nv_inference_exec_count{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s]) * 1000))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum (rate(nv_inference_compute_output_duration_us{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s])) / sum ((rate(nv_inference_exec_count{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s]) * 1000))",
     "legendFormat": "Output"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_sum{envoy_http_conn_manager_prefix=\"ingress_grpc\", app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s])) / sum(rate(envoy_http_downstream_rq_time_count{envoy_http_conn_manager_prefix=\"ingress_grpc\", app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s]))",
     "legendFormat": "Total (measured at proxy)"
    }
   ]
  },
  {
   "title": "Inferences per second (all servers, all models)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_count{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s])) by(release)",
     "legendFormat": "{{ release }}"
    }
   ]
  },
  {
   "title": "Number of Inference Servers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count by(release)(nv_gpu_utilization{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"})",
     "legendFormat": "{{release}}"
    }
   ]
  },
  { "title": "GPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "GPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nv_gpu_utilization{release=~\"$release\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU power usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(nv_gpu_power_usage{release=~\"$release\", namespace=~\"$namespace\"} / nv_gpu_power_limit{release=~\"$release\", namespace=~\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes{release=~\"$release\", namespace=~\"$namespace\"}/nv_gpu_memory_total_bytes{release=~\"$release\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Inference Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Inferences per second by server (all models)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_count{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s])) by(pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Inferences per second by model (all servers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_count{app=~\"supersonic\", release=~\"$release\", namespace=~\"$namespace\"}[30s])) by(model)",
     "legendFormat": "{{ model }}"
    }
   ]
  }
 ]
}