{{ if .Values.envoy.ingress.enabled | default false }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "supersonic.name" . }}-ingress-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
  annotations:
    {{- if .Values.envoy.ingress.annotations }}
{{ toYaml .Values.envoy.ingress.annotations | nindent 4 }}
    {{- end }}

spec:
  ingressClassName: {{ .Values.envoy.ingress.ingressClassName }}
  tls:
  - hosts:
      - {{ .Values.envoy.ingress.hostName }}
  rules:
  - host: {{ .Values.envoy.ingress.hostName }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "supersonic.name" . }}
            port:
              number: 8001
        path: /
        pathType: ImplementationSpecific

{{ end }}