{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supersonic.grafanaName" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ include "supersonic.name" . }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ include "supersonic.name" . }}
        app.kubernetes.io/component: grafana
    spec:
      containers:
        - name: grafana
          image: "grafana/grafana:10.2.3"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: "/var/lib/grafana/dashboards/default.json"
          volumeMounts:
            - name: config
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
              readOnly: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: {{ include "supersonic.grafanaName" . }}-datasources
        - name: dashboards-config
          configMap:
            name: {{ include "supersonic.grafanaName" . }}-dashboards-config
        - name: dashboards
          configMap:
            name: {{ include "supersonic.grafanaName" . }}-dashboard
{{- end }} 