{{- if and .Values.grafana.enabled (ne (include "supersonic.grafanaExists" .) "true") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supersonic.grafanaName" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: grafana
{{- end }} 