{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        isDefault: true
        {{- if .Values.prometheus.external }}
        url: {{ .Values.prometheus.scheme }}://{{ .Values.prometheus.url }}
        {{- else if .Values.prometheus.enabled }}
        url: http://{{ .Release.Name }}-prometheus-server.{{ .Release.Namespace }}.svc.cluster.local:9090
        {{- else }}
        url: http://{{ include "supersonic.prometheusName" . }}.{{ .Release.Namespace }}.svc.cluster.local:9090
        {{- end }}
        jsonData:
          timeInterval: "5s"
          {{- if and .Values.prometheus.external (eq .Values.prometheus.scheme "https") }}
          tlsSkipVerify: true
          {{- end }}
{{- end }} 