{{- if .Values.metricsCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supersonic.name" . }}-metrics-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: metrics-collector
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: metrics-collector
  ports:
  - port: 8003
    targetPort: 8003
  type: ClusterIP
{{- end }}