{{- if and .Values.prometheus.enabled (not .Values.prometheus.external.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supersonic.prometheusName" . }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.server.global.scrape_interval }}
      evaluation_interval: {{ .Values.prometheus.server.global.evaluation_interval }}

    scrape_configs:
      - job_name: 'monitoring/{{ include "supersonic.name" . }}/0'
        honor_timestamps: true
        scheme: http
        follow_redirects: true
        enable_http2: true
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - "{{ .Release.Namespace }}"
        relabel_configs:
          # Filter by app name only
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            regex: {{ .Chart.Name }}
            action: keep
          # Set metrics path based on component
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
            action: replace
            target_label: __metrics_path__
            regex: envoy
            replacement: /stats/prometheus
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
            action: replace
            target_label: __metrics_path__
            regex: triton
            replacement: /metrics
          # Add standard labels
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
            target_label: release
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            target_label: app
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

      - job_name: "{{ include "supersonic.envoyName" . }}"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - "{{ .Release.Namespace }}"
        metrics_path: /stats/prometheus
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
            regex: "envoy"
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "9901"
            action: keep
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_instance]
            target_label: release
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            target_label: app
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
{{- end }}
