{{- if not .Values.prometheus.external }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "supersonic.prometheusName" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ if not .Values.prometheus.ingress.enabled }}LoadBalancer{{ else }}ClusterIP{{ end }}
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: prometheus
{{- end }}
