{{- if and (not .Values.prometheus.external) (ne (include "supersonic.prometheusExists" .) "true") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supersonic.prometheusName" . }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'monitoring/{{ include "supersonic.name" . }}/0'
        honor_timestamps: true
        scheme: http
        follow_redirects: true
        enable_http2: true
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - "{{ .Release.Namespace }}"
        relabel_configs:
          # Filter by app name only
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            regex: {{ .Chart.Name }}
            action: keep
          # Set metrics path based on component
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
            action: replace
            target_label: __metrics_path__
            regex: envoy
            replacement: /stats/prometheus
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
            action: replace
            target_label: __metrics_path__
            regex: triton
            replacement: /metrics
          # Add standard labels
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
            target_label: component
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
            target_label: release
          - target_label: app
            replacement: {{ .Chart.Name }}
{{- end }}
