{{- if and (not .Values.prometheus.external) (ne (include "supersonic.prometheusExists" .) "true") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supersonic.prometheusName" . }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: "{{ include "supersonic.tritonName" . }}"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - "{{ .Release.Namespace }}"
        metrics_path: /metrics
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
            regex: "triton"
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8002"
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__address__]
            target_label: release
            regex: '(.*)'
            replacement: '{{ include "supersonic.name" . }}'

      - job_name: "{{ include "supersonic.envoyName" . }}"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - "{{ .Release.Namespace }}"
        metrics_path: /stats/prometheus
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
            regex: "envoy"
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "9901"
            action: keep
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__address__]
            target_label: release
            regex: '(.*)'
            replacement: '{{ include "supersonic.name" . }}'

{{- end }}
