apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "supersonic.name" . }}-triton-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: triton
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ include "supersonic.name" . }}
      app.kubernetes.io/component: triton
  endpoints:
  - port: metrics
    path: /metrics
    interval: 5s
    relabelings:
      - sourceLabels: [__address__]
        targetLabel: release
        regex: "(.*)"
        replacement: "{{ include "supersonic.name" . }}"
      - sourceLabels: [__address__]
        targetLabel: app
        regex: "(.*)"
        replacement: "{{ .Chart.Name }}"

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "supersonic.name" . }}-envoy-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: envoy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ include "supersonic.name" . }}
      app.kubernetes.io/component: envoy
  endpoints:
  - port: admin
    path: /stats/prometheus
    interval: 5s
    relabelings:
      - sourceLabels: [__address__]
        targetLabel: release
        regex: "(.*)"
        replacement: "{{ include "supersonic.name" . }}"
      - sourceLabels: [__address__]
        targetLabel: app
        regex: "(.*)"
        replacement: "{{ .Chart.Name }}"