{{- if .Values.keda.enabled }}

{{- $scaleUp := .Values.keda.scaleUp | default dict }}
{{- $scaleDown := .Values.keda.scaleDown | default dict }}
{{- $minReplicaCount := .Values.keda.minReplicaCount | int }}
{{- if eq (include "supersonic.scaleFromZeroEnabled" .) "true" }}
{{- $scaled_object := lookup "keda.sh/v1alpha1" "ScaledObject" .Release.Namespace (printf "%s-keda-so" (include "supersonic.name" .)) }}
{{- if $scaled_object }}
{{- $minReplicaCount = int (dig "spec" "minReplicaCount" $minReplicaCount $scaled_object) }}
{{- end }}
{{- end }}

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "supersonic.name" . }}-keda-so
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ include "supersonic.name" . }}
    app.kubernetes.io/component: keda
spec:
  scaleTargetRef:
    name: {{ include "supersonic.inferenceServerName" . }}
    kind: Deployment
  pollingInterval: {{ .Values.keda.pollingInterval | default 30 }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod | default 120 }}
{{- if (eq .Values.keda.zeroIdleReplicas true) }}
  idleReplicaCount: 0
{{- end }}
  minReplicaCount: {{ $minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: {{ dig "stabilizationWindowSeconds" 120 $scaleDown }}
          policies:
            - periodSeconds: {{ dig "periodSeconds" 30 $scaleDown }}
              type: Pods
              value: {{ dig "stepsize" 1 $scaleDown }}
        scaleUp:
          stabilizationWindowSeconds: {{ dig "stabilizationWindowSeconds" 120 $scaleUp }}
          policies:
            - periodSeconds: {{ dig "periodSeconds" 30 $scaleUp }}
              type: Pods
              value: {{ dig "stepsize" 1 $scaleUp }}

  triggers:
  - type: prometheus
    metricType: Value
    metadata:
      serverAddress: {{ include "supersonic.prometheusUrl" . }}
      metricName: autoscaler-metric
      threshold: {{ .Values.serverLoadThreshold | quote }}
      ignoreNullValues: "true"
      query: |-
        {{ include "supersonic.defaultMetric" . | nindent 8 }}
---

{{- end }}