apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: cvmfs
provisioner: cvmfs.csi.cern.ch

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    # Has no effect as Read-Only Access: must be non-zero.
    requests:
      storage: 1
  storageClassName: cvmfs