apiVersion: v1
kind: ServiceAccount
metadata:
  name: super-sonic-ci-sa
  namespace: cms
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: super-sonic-ci-role
  namespace: cms
rules:
  - apiGroups: ['']
    resources: ['pods', 'services', 'configmaps', 'secrets']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch', 'delete']
  - apiGroups: ['apps']
    resources: ['deployments', 'statefulsets', 'daemonsets', 'replicasets']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch', 'delete']
  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch', 'delete']
  - apiGroups: ['networking.k8s.io']
    resources: ['ingresses', 'networkpolicies']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch', 'delete']
  - apiGroups: ['monitoring.coreos.com']
    resources: ['servicemonitors']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch', 'delete']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: super-sonic-ci-binding
  namespace: cms
roleRef:
  kind: Role
  name: super-sonic-ci-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: super-sonic-ci-sa
    namespace: cms