apiVersion: v2
name: supersonic
description: Server infrastructure for inference-as-a-service in large scientific experiments.
icon: https://github.com/fastmachinelearning/SuperSONIC/blob/master/docs/img/SuperSONIC_small_512.png?raw=true
version: 0.1.0
type: application
home: https://fastmachinelearning.org/SuperSONIC/
annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/links: |
    - name: GitHub
      url: https://github.com/fastmachinelearning/SuperSONIC/
