name: ci [installer plugin]

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  test-installer-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes cluster with Kind
        uses: helm/kind-action@v1.6.0
        with:
          cluster_name: gh-k8s-cluster

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Create CMS namespace
        run: |
          kubectl create namespace cms

      - name: Install Prometheus Operator CRDs
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          kubectl create namespace monitoring
          helm install prometheus-operator prometheus-community/kube-prometheus-stack --namespace monitoring --set prometheusOperator.createCustomResource=false --set defaultRules.create=false --set alertmanager.enabled=false --set prometheus.enabled=false --set grafana.enabled=false

      - name: Install KEDA Autoscaler
        run: |
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          kubectl create namespace keda
          helm install keda kedacore/keda --namespace keda  

      - name: Install SuperSONIC from remote repo via plugin
        run: |
          helm plugin install .
          helm install-supersonic supersonic --local --values values/values-cms-ci.yaml -n cms

      - name: Cleanup
        run: kind delete cluster --name gh-k8s-cluster 