name: ci [installation]

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  test-installation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes cluster with Kind
        uses: helm/kind-action@v1.6.0
        with:
          cluster_name: gh-k8s-cluster

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Create test namespace
        run: |
          kubectl create namespace test-ns

      # - name: Test installation of SuperSONIC from remote repo 
      #   run: |
      #     helm repo add fastml https://fastmachinelearning.org/SuperSONIC/
      #     helm repo update
      #     helm install supersonic fastml/supersonic -n test-ns -f values/values-minimal.yaml
      #     helm uninstall supersonic -n test-ns

      - name: Test installation of SuperSONIC from GitHub
        run: |
          # Add dependencies
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add opentelemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo update

          # Install SuperSONIC
          helm dependency build helm/supersonic
          helm install supersonic helm/supersonic -n test-ns -f values/values-minimal.yaml
          helm uninstall supersonic -n test-ns

      - name: Cleanup
        run: kind delete cluster --name gh-k8s-cluster 