name: helm docs

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: 
      - "master"

jobs:
  helm-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      # Install helm-docs
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
      - run: |
          go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest
          export PATH=$PATH:$(go env GOPATH)/bin

      # Run helm-docs
      - name: Run helm-docs
        run: |
          helm-docs --chart-search-root=helm/supersonic \
            --template-files=../../docs/.values-table.md.gotmpl \
            --output-file=../../docs/.values-table.md \
            --sort-values-order=file
            

      - name: Copy README.md from root
        run: |
          cp README.md helm/supersonic/README.md

      # Commit and push changes to the same branch
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git user
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Add and commit changes
          git pull
          git add helm/supersonic/README.md docs/.values-table.md
          git commit -m "Update helm docs" || echo "No changes to commit"

          # Push changes back to the same branch
          git push origin HEAD:${{ github.head_ref || github.ref }}