name: Release Helm Chart

on:
  push:
    branches:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: fastmachinelearning
          repo: SuperSONIC
          pages_branch: gh-pages
          pages_directory: charts
          charts_dir: helm