name: docs

on:
  push:
    branches:
      - "**"
      # - "master"
      # - "docs"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx documentation
        run: |
          sphinx-build docs/ docs/_build/html

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
  
      - name: Create docs-build directory if not present
        run: mkdir -p docs-build

      - name: Copy build files to docs-build
        run: cp -r docs/_build/html/* docs-build/

      - name: Add CNAME file for custom domain
        run: echo "fastmachinelearning.org/SuperSONIC" > docs-build/CNAME

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure Git user
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add docs-build
          git commit -m "Update Sphinx documentation" || echo "No changes to commit"
          git push origin gh-pages